name: Create IAM Role and Policy

on: 
  push:
    branches: [ main ]

jobs:
  create-iam-user-and-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Create users
      run: |
        aws iam create-user --user-name MyGitHubActionUser

    - name: Create Login Profile
      run: |
        aws iam create-login-profile --user-name MyGitHubActionUser --password ${{ secrets.IAM_PASSWORD }} 

    - name: Create Access Key
      run: |
        aws iam create-access-key --user-name MyGitHubActionUser

    - name: create a bucket
      run: |
        aws s3 mb s3://healerbucket

    - name: Create IAM Policy
      run: |
        cat <<EoF > user-policy.json
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject"
              ],
              "Resource": "*"
            }
          ]
        }
        EoF

        aws iam create-policy --policy-name MyGitHubActionPolicy --policy-document file://user-policy.json

    - name: Attach IAM Policy to user
      run: |
        POLICY_ARN=$(aws iam list-policies --query 'Policies[?PolicyName==MyGitHubActionPolicy].Arn' --output text)
        aws iam attach-role-policy --role-name MyGitHubActionRole --policy-arn $POLICY_ARN

