name: Create IAM Role and Policy

on: 
  push:
    branches: [ main ]

jobs:
  create-iam-user-and-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Create users
      run: |
        aws iam create-user --user-name jaylen

    - name: Create Login Profile
      run: |
        aws iam create-login-profile --user-name jaylen --password ${{ secrets.IAM_PASSWORD }} --password-reset-required

    - name: Create Access Key
      id: create_access_key
      run: |
        aws iam create-access-key --user-name jaylen > access_key.json
        cat access_key.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    
    - name: create a bucket
      run: |
        aws s3 mb s3://healerbucket

    - name: Create IAM Policy
      id: create_policy
      run: |
        cat <<EoF > user-policy.json
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject"
              ],
              "Resource": "arn:aws:s3:::healerbucket/*"
            }
          ]
        }
        EoF

        POLICY_ARN=$(aws iam create-policy --policy-name GitHubAction --policy-document file://user-policy.json --query 'Policy.Arn' --output text)
        echo "POLICY_ARN=$POLICY_ARN" >> $GITHUB_ENV

    - name: Attach IAM Policy to user
      run: |
        aws iam attach-user-policy --user-name jaylen --policy-arn ${{ env.POLICY_ARN }}


    
        
        