name: Create IAM Role and Policy

on: 
  push:
    branches: [ main ]

jobs:
  create-iam-user-and-policy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Create users
      run: |
        aws iam create-user --user-name tatum

    - name: Create Login Profile
      run: |
        aws iam create-login-profile --user-name tatum --password ${{ secrets.IAM_PASSWORD }} 

    - name: Create Access Key
      run: |
        aws iam create-access-key --user-name tatum

    - name: create a bucket
      run: |
        aws s3 mb s3://healerbucket

    - name: Create IAM Policy
      run: |
        cat <<EoF > user-policy.json
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject"
              ],
              "Resource": "*"
            }
          ]
        }
        EoF

        Arn=`aws iam create-policy --policy-name GitHubActionPolicyss --policy-document file://user-policy.json | grep Arn`

        POLICY_ARN=$(echo $Arn | cut -d ":" -f2)


    - name: Attach IAM Policy to user
      run: |
        aws iam attach-user-policy --user-name tatum --policy-arn $POLICY_ARN

    
        
        